name: backend_firestore
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  firebase_admin: ^0.3.1
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  mongo_dart: ^0.10.0
  dart_jsonwebtoken: ^3.2.0
  dotenv: ^4.2.0
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
